import type { BattleResult, Environment, Fighter } from "./types";

export type MatchVariant="standard"|"random"|"daily"|"best_of_three";
export interface MatchRecord{id:string;playedAt:string;variant:MatchVariant;playerId:string;playerName:string;opponentId:string;opponentName:string;environment:Environment;winner:BattleResult["winner"];margin:number}
export interface ProgressionState{history:MatchRecord[];favorites:string[];achievements:string[];discoveredTraits:string[]}
export const EMPTY_PROGRESSION:ProgressionState={history:[],favorites:[],achievements:[],discoveredTraits:[]};
const environments:Environment[]=["Neutral","Salty","Alkaline","Hot","Cold","Acidic","In the presence of antibiotics"];
export function dailySeed(date=new Date()){return Number(date.toISOString().slice(0,10).replaceAll("-",""))}
export function dailyEnvironment(date=new Date()){return environments[dailySeed(date)%environments.length]}
export function achievementsFor(history:MatchRecord[],player:Fighter,opponent:Fighter,environment:Environment){const unlocked=new Set<string>();if(history.length>=1)unlocked.add("First Culture");if(new Set(history.map(item=>item.environment)).size>=4)unlocked.add("Habitat Explorer");if(new Set(history.flatMap(item=>[item.playerId,item.opponentId])).size>=10)unlocked.add("Microbe Naturalist");if((player.cellShape||"")!==(opponent.cellShape||""))unlocked.add("Morphology Mixer");if(environment!=="Neutral")unlocked.add("Adaptation Observer");return [...unlocked]}
export function appendMatch(state:ProgressionState,record:MatchRecord,player:Fighter,opponent:Fighter){const history=[record,...state.history.filter(item=>item.id!==record.id)].slice(0,50),traits=[...new Set([...state.discoveredTraits,...player.traits.map(item=>item.trait),...opponent.traits.map(item=>item.trait)])].sort();return{...state,history,discoveredTraits:traits,achievements:[...new Set([...state.achievements,...achievementsFor(history,player,opponent,record.environment)])].sort()}}
export function toggleFavorite(state:ProgressionState,id:string){return{...state,favorites:state.favorites.includes(id)?state.favorites.filter(item=>item!==id):[...state.favorites,id]}}
export async function shareResultCard(record:MatchRecord){if(typeof document==="undefined")return;const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1080;const context=canvas.getContext("2d");if(!context)return;const gradient=context.createLinearGradient(0,0,1080,1080);gradient.addColorStop(0,"#071a16");gradient.addColorStop(1,"#173c31");context.fillStyle=gradient;context.fillRect(0,0,1080,1080);context.fillStyle="#7bf2bc";context.font="700 42px system-ui";context.fillText("MICROBIAL MAYHEM",70,100);context.fillStyle="#ffffff";context.font="700 62px system-ui";context.fillText(record.winner==="tie"?"EVENLY MATCHED":record.winner==="A"?"PLAYER 1 THRIVES":"RIVAL THRIVES",70,210);context.font="italic 42px Georgia";context.fillText(record.playerName,70,350);context.fillStyle="#ff755f";context.fillText("VS",70,430);context.fillStyle="#ffffff";context.fillText(record.opponentName,70,510);context.fillStyle="#d7f171";context.font="700 36px system-ui";context.fillText(record.environment,70,650);context.fillStyle="#bfd0c7";context.font="30px system-ui";context.fillText("A biologically grounded Petri-dish matchup",70,735);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/png"));if(!blob)return;const file=new File([blob],"microbial-mayhem-result.png",{type:"image/png"});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:"Microbial Mayhem result",files:[file]}).catch(()=>undefined);return}const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=file.name;link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}
