"use client";

import { useEffect, useRef } from "react";
import { BATTLE_CUES, BATTLE_DURATION_MS, CompletionGate, battleHealth } from "../game/battle-timeline";
import type { BattleResult, Environment, Fighter } from "../game/types";
import { differentiatedDuelProfiles, fighterVisualProfile, livingColonyCount, type BattlePose } from "../game/visual-profile";
import { QUALITY_LIMITS, type QualityTier } from "../game/performance";

type ArenaProps={
  paused?:boolean;reducedMotion?:boolean;quality?:QualityTier;environment:Environment;
  player:Fighter;opponent:Fighter;playerCfu:number;opponentCfu:number;
  playerArsenal:boolean;opponentArsenal:boolean;result:BattleResult;seed:number;
  onComplete:()=>void;onCue?:(kind:string)=>void;
};
type Profile=ReturnType<typeof fighterVisualProfile>;

export function PhaserArena({paused=false,reducedMotion=false,quality="high",environment,player,opponent,playerCfu,opponentCfu,playerArsenal,opponentArsenal,result,seed,onComplete,onCue}:ArenaProps){
  const host=useRef<HTMLDivElement>(null),gameRef=useRef<import("phaser").Game>(),pausedRef=useRef(paused),callback=useRef(onComplete),cueCallback=useRef(onCue);
  callback.current=onComplete;cueCallback.current=onCue;
  useEffect(()=>{pausedRef.current=paused;const game=gameRef.current;if(!game)return;if(paused)game.scene.pause("BattleScene");else game.scene.resume("BattleScene")},[paused]);
  useEffect(()=>{
    let game:import("phaser").Game|undefined,disposed=false;const gate=new CompletionGate(),limits=QUALITY_LIMITS[quality],[playerProfile,opponentProfile]=differentiatedDuelProfiles(player,opponent);
    void import("phaser").then(({default:Phaser})=>{if(disposed||!host.current)return;
      type Cell={body:Phaser.GameObjects.Container;shadow:Phaser.GameObjects.Ellipse;baseX:number;baseY:number;rank:number};
      class BattleScene extends Phaser.Scene{
        left:Cell[]=[];right:Cell[]=[];label!:Phaser.GameObjects.Text;impact!:Phaser.GameObjects.Arc;shield!:Phaser.GameObjects.Ellipse;leftBar!:Phaser.GameObjects.Rectangle;rightBar!:Phaser.GameObjects.Rectangle;leftCount!:Phaser.GameObjects.Text;rightCount!:Phaser.GameObjects.Text;leftTerritory!:Phaser.GameObjects.Ellipse;rightTerritory!:Phaser.GameObjects.Ellipse;
        color(value:string){return Number.parseInt(value.slice(1),16)}
        cellArt(profile:Profile,scale:number,flip:boolean){
          const color=this.color(profile.primary),accent=this.color(profile.secondary),shape=profile.shape,side=flip?-1:1,details:Phaser.GameObjects.GameObject[]=[];
          const dimensions=shape==="coccus"?[76,76]:shape==="cluster"?[112,88]:shape==="chain"?[150,48]:shape==="filament"?[170,46]:shape==="spiral"?[148,48]:shape==="vibrio"||shape==="curved"?[122,58]:shape==="rod"||shape==="capsule"||shape==="spore"?[136,62]:[112,74];
          const body=this.add.ellipse(0,0,dimensions[0],dimensions[1],color,.78).setStrokeStyle(3,accent,.92);details.push(body);
          if(shape==="cluster"){body.setAlpha(.12);for(const [x,y] of [[-34,-22],[25,-25],[-38,22],[30,20],[0,0]])details.push(this.add.circle(x,y,25,color,.78).setStrokeStyle(2,accent,.9))}
          else if(shape==="chain"){body.setAlpha(.06);for(let i=-3;i<=3;i++)details.push(this.add.circle(i*21,Math.sin(i)*7,17,i%2?accent:color,.8).setStrokeStyle(2,accent))}
          else if(shape==="filament"||shape==="spiral")body.setFillStyle(color,.1).setStrokeStyle(shape==="spiral"?8:5,accent,.95);
          else if(shape==="vibrio"||shape==="curved"){body.setAngle(-18);details.push(this.add.arc(5,4,dimensions[0]*.42,195,340,false,color,.18).setStrokeStyle(7,accent,.8))}
          if(profile.texture==="speckled"||profile.texture==="granular")for(const [x,y] of [[-24,-12],[18,-15],[29,13],[-10,17]])details.push(this.add.circle(x,y,3,0xffffff,.48));
          else if(profile.texture==="banded")for(const x of [-28,0,28])details.push(this.add.rectangle(x,0,4,dimensions[1]*.7,accent,.32));
          if(shape==="spore")details.push(this.add.ellipse(10,0,30,42,0xffffff,.22).setStrokeStyle(3,accent,.85));
          if(shape==="capsule")details.push(this.add.ellipse(0,0,dimensions[0]+22,dimensions[1]+20,accent,.08).setStrokeStyle(6,accent,.32));
          const appendage=this.add.graphics().lineStyle(profile.appendage==="tuft"?5:3,accent,.82);
          if(profile.appendage==="polar"||profile.appendage==="tuft"){appendage.lineBetween(side*dimensions[0]*.45,0,side*dimensions[0]*.72,-15).lineBetween(side*dimensions[0]*.72,-15,side*dimensions[0],10);if(profile.appendage==="tuft")appendage.lineBetween(side*dimensions[0]*.5,8,side*dimensions[0]*.9,25)}
          else if(profile.appendage==="peritrichous"||profile.appendage==="pili")for(let i=-2;i<=2;i++)appendage.lineBetween(i*19,-dimensions[1]*.4,i*25,-dimensions[1]*.72);
          details.push(appendage,this.add.circle(-15,-6,5,0x06120f),this.add.circle(15,-6,profile.expression==="curious"?7:5,0x06120f),this.add.arc(0,12,profile.expression==="bold"?12:9,0,180,false,0x06120f,0).setStrokeStyle(2,0x06120f));
          return this.add.container(0,0,details).setScale(scale*(flip?-1:1),scale).setAngle(profile.tilt);
        }
        makeColony(side:"left"|"right",profile:Profile,cfu:number){
          const flip=side==="right",centerX=this.scale.width*(flip?.73:.27),centerY=this.scale.height*.54,full=livingColonyCount(cfu,100,limits.colony),cells:Cell[]=[];
          for(let i=0;i<full;i++){const rank=i/full,ring=Math.sqrt(rank),angle=i*2.399963+seed*.017+(flip?1.4:0),spreadX=(90+Math.min(175,cfu*.13))*ring,spreadY=(42+Math.min(88,cfu*.055))*ring,x=centerX+Math.cos(angle)*spreadX,y=centerY+55+Math.sin(angle)*spreadY,perspective=.23+rank*.16+(i===0?.22:0),shadow=this.add.ellipse(x,y+18,82*perspective,22*perspective,0x000000,.28).setDepth(5+Math.round(y)),body=this.cellArt(profile,perspective,flip).setPosition(x,y).setDepth(6+Math.round(y)).setAlpha(0);body.setData("baseScale",perspective).setData("flip",flip).setData("profile",profile);cells.push({body,shadow,baseX:x,baseY:y,rank})}
          return cells;
        }
        pose(cells:Cell[],pose:BattlePose){
          const duration=reducedMotion?60:pose==="attack"?170:pose==="victory"?420:260;
          cells.forEach((cell,index)=>{const base=cell.body.getData("baseScale") as number,flip=cell.body.getData("flip") as boolean,direction=flip?-1:1,delay=reducedMotion?0:Math.min(150,index*8);let scaleX=base*(flip?-1:1),scaleY=base,x=cell.baseX,y=cell.baseY,angle=(cell.body.getData("profile") as Profile).tilt,alpha=1;
            if(pose==="ready"){scaleX*=1.04;scaleY*=.96;x+=direction*7}if(pose==="move")x+=direction*22;if(pose==="anticipate"){scaleX*=.82;scaleY*=1.14;x-=direction*12}if(pose==="attack"){scaleX*=1.24;scaleY*=.82;x+=direction*(44+cell.rank*25)}if(pose==="defend"){scaleX*=.9;scaleY*=1.1;x-=direction*8}if(pose==="impact"){scaleX*=.76;scaleY*=1.2;x-=direction*24}if(pose==="arsenal"){scaleX*=1.16;scaleY*=1.16;y-=12}if(pose==="stress"){scaleX*=.9;scaleY*=1.08;angle+=index%2?5:-5;alpha=.72}if(pose==="decline"){scaleX*=.82;scaleY*=.82;y+=12;alpha=.45}if(pose==="recover"){scaleX*=1.13;scaleY*=1.13;y-=8}if(pose==="victory"){y-=18+(index%4)*7;angle+=direction*(index%2?8:-8)}if(pose==="defeat"){scaleX*=.72;scaleY*=.55;y+=18;angle+=direction*18;alpha=.42}
            const yoyo=["ready","move","anticipate","attack","defend","impact","arsenal","stress","recover"].includes(pose);this.tweens.add({targets:cell.body,x,y,scaleX,scaleY,angle,alpha,duration,delay,ease:"Sine.easeOut",yoyo});this.tweens.add({targets:cell.shadow,x,y:y+18,scaleX:pose==="attack"?.82:pose==="victory"?.7:1,alpha:pose==="defeat"?.12:.28,duration,delay,ease:"Sine.easeOut",yoyo})});
        }
        reveal(cells:Cell[],side:"left"|"right"){const start=side==="left"?-170:this.scale.width+170;cells.forEach((cell,index)=>{cell.body.x=start;cell.shadow.x=start;cell.shadow.setAlpha(0);this.tweens.add({targets:cell.body,x:cell.baseX,alpha:1,duration:reducedMotion?60:440+index*7,delay:index*6,ease:"Cubic.easeOut"});this.tweens.add({targets:cell.shadow,x:cell.baseX,alpha:.28,duration:reducedMotion?60:440+index*7,delay:index*6})});this.time.delayedCall(reducedMotion?70:520,()=>this.pose(cells,"ready"))}
        setPopulation(cells:Cell[],health:number,cfu:number,side:"left"|"right"){const visible=livingColonyCount(cfu,health,limits.colony);cells.forEach((cell,index)=>{const live=index<visible;if(!live&&cell.body.visible)this.tweens.add({targets:[cell.body,cell.shadow],alpha:0,scaleX:"*=.7",scaleY:"*=.7",duration:reducedMotion?50:240,onComplete:()=>{cell.body.setVisible(false);cell.shadow.setVisible(false)}});else if(live&&!cell.body.visible){cell.body.setVisible(true).setAlpha(0);cell.shadow.setVisible(true).setAlpha(0);this.tweens.add({targets:cell.body,alpha:1,duration:reducedMotion?50:280});this.tweens.add({targets:cell.shadow,alpha:.28,duration:reducedMotion?50:280})}});(side==="left"?this.leftCount:this.rightCount).setText(`${cfu.toLocaleString()} CFU · ${visible} visible cells`)}
        environmentFx(width:number,height:number){const color=environment==="Cold"?0xc9f4ff:environment==="Hot"?0xff755f:environment==="Salty"?0xefe8ca:environment==="Alkaline"?0x8ff3d1:environment==="Acidic"?0xd7f171:environment.includes("antibiotics")?0xff7894:0x7bf2bc;for(let i=0;i<limits.particles;i++){const x=(i*83+seed)%width,y=92+(i*59)%(height-150);let shape:Phaser.GameObjects.Shape;if(environment==="Salty")shape=this.add.rectangle(x,y,8,8,color,.48).setAngle(45);else if(environment==="Alkaline")shape=this.add.polygon(x,y,[0,-8,7,0,0,8,-7,0],color,.34).setStrokeStyle(1,color);else if(environment.includes("antibiotics")){shape=this.add.rectangle(x,y,18,4,color,.52);this.add.rectangle(x,y,4,18,color,.52)}else if(environment==="Cold")shape=this.add.star(x,y,6,2,8,color,.48);else shape=this.add.circle(x,y,3+i%4,color,.38).setStrokeStyle(environment==="Acidic"?2:0,color);shape.setDepth(4+(i%3)*3);if(!reducedMotion)this.tweens.add({targets:shape,y:y+(environment==="Hot"?-52:environment==="Cold"?18:-26),scale:environment==="Acidic"?1.8:1.15,angle:environment==="Salty"||environment==="Alkaline"?90:0,duration:1500+(i%5)*280,yoyo:true,repeat:-1,ease:"Sine.inOut",delay:i*50})}if(environment.includes("antibiotics")){const scan=this.add.rectangle(width/2,112,width,10,color,.12).setDepth(1400);if(!reducedMotion)this.tweens.add({targets:scan,y:height-70,duration:2100,repeat:-1,yoyo:true})}}
        layers(){const {width,height}=this.scale,bg=this.add.graphics(),top=environment==="Cold"?0x102f49:environment==="Hot"?0x421b17:environment==="Acidic"?0x263213:environment==="Alkaline"?0x123d36:environment==="Salty"?0x1b3540:environment.includes("antibiotics")?0x29172b:0x102d25;bg.fillGradientStyle(0x030b0a,top,0x1d1511,0x020807,1).fillRect(0,0,width,height).setDepth(0);this.add.ellipse(width/2,height*.64,width*.95,height*.72,0x000000,.42).setDepth(1);this.add.ellipse(width/2,height*.56,width*.94,height*.78,0xbefee6,.045).setStrokeStyle(18,0xddfff2,.16).setDepth(2);const fluid=this.add.ellipse(width/2,height*.56,width*.87,height*.68,top,.56).setStrokeStyle(3,0xa8ebcf,.22).setDepth(3);this.leftTerritory=this.add.ellipse(width*.27,height*.6,width*.43,height*.46,this.color(playerProfile.primary),.08).setDepth(4);this.rightTerritory=this.add.ellipse(width*.73,height*.6,width*.43,height*.46,this.color(opponentProfile.primary),.08).setDepth(4);const glass=this.add.ellipse(width/2,height*.53,width*.91,height*.72,0xffffff,.018).setStrokeStyle(4,0xffffff,.2).setDepth(1500);this.add.arc(width*.37,height*.31,width*.3,198,330,false,0xffffff,0).setStrokeStyle(6,0xffffff,.1).setScale(1,.32).setDepth(1501);if(!reducedMotion)this.tweens.add({targets:[fluid,glass],scaleX:1.012,scaleY:.988,duration:3400,yoyo:true,repeat:-1,ease:"Sine.inOut"})}
        create(){const {width}=this.scale;this.layers();this.environmentFx(width,this.scale.height);this.left=this.makeColony("left",playerProfile,playerCfu);this.right=this.makeColony("right",opponentProfile,opponentCfu);this.impact=this.add.circle(width*.5,this.scale.height*.5,8,0xffffff,.9).setVisible(false).setDepth(1700);this.shield=this.add.ellipse(width*.7,this.scale.height*.56,210,145,0x7bf2bc,.06).setStrokeStyle(5,0x7bf2bc,.7).setVisible(false).setDepth(1450);this.label=this.add.text(width/2,this.scale.height*.14,"",{fontFamily:"system-ui",fontSize:"21px",fontStyle:"bold",color:"#effff6",backgroundColor:"#04110edd",padding:{x:16,y:9}}).setOrigin(.5).setAlpha(0).setDepth(1900);this.add.rectangle(55,38,330,10,0x243d35).setOrigin(0,.5).setDepth(1900);this.add.rectangle(width-385,38,330,10,0x243d35).setOrigin(0,.5).setDepth(1900);this.leftBar=this.add.rectangle(55,38,330,10,this.color(playerProfile.primary)).setOrigin(0,.5).setDepth(1901);this.rightBar=this.add.rectangle(width-385,38,330,10,this.color(opponentProfile.primary)).setOrigin(0,.5).setDepth(1901);this.leftCount=this.add.text(55,52,`${playerCfu.toLocaleString()} CFU · ${this.left.length} visible cells`,{fontFamily:"system-ui",fontSize:"13px",color:playerProfile.secondary}).setDepth(1901);this.rightCount=this.add.text(width-55,52,`${opponentCfu.toLocaleString()} CFU · ${this.right.length} visible cells`,{fontFamily:"system-ui",fontSize:"13px",color:opponentProfile.secondary}).setOrigin(1,0).setDepth(1901);BATTLE_CUES.forEach(([at,kind])=>this.time.delayedCall(reducedMotion?Math.min(450,at/12):at,()=>this.cue(kind)));this.time.delayedCall(reducedMotion?600:BATTLE_DURATION_MS,()=>gate.finish(()=>callback.current()))}
        announce(text:string){this.label.setText(text).setAlpha(1).setY(this.scale.height*.14+8);this.tweens.add({targets:this.label,alpha:0,y:this.label.y-8,duration:reducedMotion?80:650,delay:reducedMotion?30:370})}
        ripple(x:number,y:number,color:number,strong=false){for(let i=0;i<(strong?3:2);i++){const ring=this.add.ellipse(x,y,30,14,color,0).setStrokeStyle(strong?5:3,color,.78).setDepth(1550);this.tweens.add({targets:ring,scale:strong?8:5,alpha:0,duration:reducedMotion?70:320+i*90,delay:i*55,onComplete:()=>ring.destroy()})}}
        projectile(from:Cell[],to:Cell[],color:number,strong=false){const actor=from[0].body,target=to[0].body,trail=Array.from({length:strong?8:5},(_,i)=>this.add.circle(actor.x,actor.y,strong?8-i*.5:5,color,1-i*.09).setDepth(1600)),controlY=(actor.y+target.y)/2-(strong?145:90),driver={t:0};this.tweens.add({targets:driver,t:1,duration:reducedMotion?70:strong?390:310,onUpdate:()=>{const t=driver.t,u=1-t,x=u*u*actor.x+2*u*t*(actor.x+target.x)/2+t*t*target.x,y=u*u*actor.y+2*u*t*controlY+t*t*target.y;trail.forEach((dot,index)=>dot.setPosition(x-(actor.x<target.x?1:-1)*index*11,y+Math.sin(index)*4))},onComplete:()=>{trail.forEach(dot=>dot.destroy());this.hit(to,strong)}})}
        hit(target:Cell[],strong=false){const lead=target[0].body;this.pose(target,"impact");this.impact.setPosition(lead.x,lead.y).setScale(1).setAlpha(1).setVisible(true);this.tweens.add({targets:this.impact,scale:strong?13:8,alpha:0,duration:reducedMotion?70:280,onComplete:()=>this.impact.setVisible(false)});this.ripple(lead.x,lead.y+36,strong?0xffe28a:0xffffff,strong);if(!reducedMotion)this.cameras.main.shake(strong?135:80,strong?.006:.0035)}
        arsenal(cells:Cell[],active:boolean,color:number){this.pose(cells,active?"arsenal":"recover");if(!active)return;cells.slice(0,12).forEach((cell,index)=>{const halo=this.add.circle(cell.body.x,cell.body.y,18,color,.08).setStrokeStyle(2,color,.55).setDepth(1450);this.tweens.add({targets:halo,scale:2.8,alpha:0,duration:reducedMotion?70:430,delay:index*18,onComplete:()=>halo.destroy()})})}
        cue(kind:string){cueCallback.current?.(kind);const progress=(BATTLE_CUES.find(c=>c[1]===kind)?.[0]||0)/BATTLE_DURATION_MS,[a,b]=battleHealth(progress,result.winner);this.leftBar.width=330*a/100;this.rightBar.width=330*b/100;this.setPopulation(this.left,a,playerCfu,"left");this.setPopulation(this.right,b,opponentCfu,"right");
          if(kind==="entrance"){this.announce("Living colonies enter the dish");this.reveal(this.left,"left");this.reveal(this.right,"right")}if(kind==="anticipate"){this.announce("Both colonies take a ready stance");this.pose(this.left,"anticipate");this.pose(this.right,"anticipate")}if(kind==="attack"){this.announce("Player colony advances");this.pose(this.left,"attack");this.projectile(this.left,this.right,0xff755f)}if(kind==="defend"){this.announce("Rival colony braces");this.pose(this.right,"defend");this.shield.setVisible(true).setAlpha(.75);this.tweens.add({targets:this.shield,scale:1.25,alpha:0,duration:500,onComplete:()=>this.shield.setVisible(false)})}if(kind==="counter"){this.announce("Rival colony counterattacks");this.pose(this.right,"attack");this.projectile(this.right,this.left,0x7bf2bc)}if(kind==="dodge"){this.announce("The colony shifts formation");this.pose(this.left,"move")}if(kind==="playerAbility"){this.announce(playerArsenal?"Player arsenal activated":"Player adaptation");this.arsenal(this.left,playerArsenal,this.color(playerProfile.secondary));this.projectile(this.left,this.right,0xd7f171,playerArsenal)}if(kind==="environment"){this.announce(`${environment} pressure affects both colonies`);this.pose(this.left,"stress");this.pose(this.right,"stress")}if(kind==="opponentAbility"){this.announce(opponentArsenal?"Rival arsenal activated":"Rival adaptation");this.arsenal(this.right,opponentArsenal,this.color(opponentProfile.secondary));this.projectile(this.right,this.left,0xb99cff,opponentArsenal)}if(kind==="pause"){this.announce("The colonies regroup");this.pose(this.left,"recover");this.pose(this.right,"recover")}if(kind==="finish"){this.announce(result.winner==="tie"?"Final colony clash":"Decisive colony surge");this.pose(result.winner==="A"?this.left:result.winner==="B"?this.right:[...this.left,...this.right],"attack");this.ripple(this.scale.width/2,this.scale.height*.52,0xffe28a,true);if(!reducedMotion){this.cameras.main.zoomTo(1.065,170,"Sine.easeOut",true);this.time.delayedCall(210,()=>this.cameras.main.zoomTo(1,320,"Sine.easeInOut",true))}}if(kind==="resolution"){const [fa,fb]=battleHealth(1,result.winner);this.setPopulation(this.left,fa,playerCfu,"left");this.setPopulation(this.right,fb,opponentCfu,"right");if(result.winner==="A"){this.pose(this.left,"victory");this.pose(this.right,"defeat")}else if(result.winner==="B"){this.pose(this.left,"defeat");this.pose(this.right,"victory")}else{this.pose(this.left,"decline");this.pose(this.right,"decline")}this.tweens.add({targets:this.leftTerritory,scale:result.winner==="A"?1.55:.75,alpha:result.winner==="A"?.22:.04,duration:550});this.tweens.add({targets:this.rightTerritory,scale:result.winner==="B"?1.55:.75,alpha:result.winner==="B"?.22:.04,duration:550});this.announce(result.winner==="tie"?"Both colonies reach equilibrium":"The surviving colony claims the agar")}}
      }
      game=new Phaser.Game({type:Phaser.AUTO,parent:host.current!,transparent:true,width:1000,height:500,scene:BattleScene,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},render:{antialias:limits.antialias,pixelArt:false},audio:{noAudio:true}});gameRef.current=game;
    });
    const visibility=()=>{const active=gameRef.current;if(!active)return;if(document.hidden)active.scene.pause("BattleScene");else if(!pausedRef.current)active.scene.resume("BattleScene")};document.addEventListener("visibilitychange",visibility);return()=>{disposed=true;document.removeEventListener("visibilitychange",visibility);gameRef.current=undefined;game?.destroy(true)};
  },[reducedMotion,quality,environment,player,opponent,playerCfu,opponentCfu,playerArsenal,opponentArsenal,result.winner,seed]);
  return <div ref={host} className={`phaser-arena living-colony-arena arena-${environment.replaceAll(" ","-").toLowerCase()}`} role="img" aria-label={`Scripted microscopic colony battle between ${player.fullName}, ${playerCfu} CFU, and ${opponent.fullName}, ${opponentCfu} CFU`}/>;
}
